# Generated by Django 3.0.7 on 2020-06-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20200610_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_video', to='show.Video'),
        ),
    ]
