# Generated by Django 3.0.7 on 2020-06-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20200610_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='show.Video'),
        ),
    ]
